title: Ben's Digital Garden

include: ['_pages']
exclude: [
  'LICENSE',
  'netlify.toml',
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  '_includes/notes_graph.json'
]
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: true

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-katex
  - jekyll-mermaid

mermaid:
  src: 'assets/mermaid.min.js'

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
